"""
Pack records and the gate that decides what may reach ``training-ready/``.

A pack serves two audiences: diligence (prove this is what you say it is, and
that you had the right to release it) and utility (a folder a buyer can train
from directly). The record is the unit that serves both — it binds upward to the
sealed bundle that produced it and downward to the rows in the training files.

Admissibility is an **allow-list**, not a deny-list. A rights status, privacy
status or review value that nobody has explicitly declared admissible blocks
release. That way a new vocabulary term, a typo, or an unmigrated record fails
closed rather than slipping through because nothing named it as bad.

The five blocking conditions:

1. ``rights_status`` is not explicitly admissible (``UNKNOWN`` is the default);
2. ``authorship_class`` is ``mixed`` — split the record first;
3. ``privacy_status`` has not passed a scan;
4. any of the record's conservative split-lineage keys also appears in the
   held-out split;
5. the source ingot is quarantined, or its Foundry evaluation was not ``PASS``.

Model reasoning is handled by policy rather than a hardcoded rule, because
whether to exclude it at capture or gate it at release is an operator decision.
The default excludes it.
"""

from __future__ import annotations

import hashlib
import json
import re
from dataclasses import dataclass, field
from typing import Any, Iterable

from .paths import find_contract

V1_SCHEMA_ID = "gtdataworks.pack.record.v1"
V2_SCHEMA_ID = "gtdataworks.pack.record.v2"
V3_SCHEMA_ID = "gtdataworks.pack.record.v3"
V1_CONTRACT_FILENAME = "pack-record.v1.schema.json"
V2_CONTRACT_FILENAME = "pack-record.v2.schema.json"
V3_CONTRACT_FILENAME = "pack-record.v3.schema.json"

# New arena producers still emit v2. Validation is version-routed so a v1 or v2
# record is checked against the contract it declared. v3 admits RIGHTS_ASSERTED
# only when Foundry status is PASS; it does not change v2.
SCHEMA_ID = V2_SCHEMA_ID
CONTRACT_FILENAME = V2_CONTRACT_FILENAME
SUPPORTED_SCHEMA_IDS = frozenset({V1_SCHEMA_ID, V2_SCHEMA_ID, V3_SCHEMA_ID})
CONTRACT_FILENAMES = {
    V1_SCHEMA_ID: V1_CONTRACT_FILENAME,
    V2_SCHEMA_ID: V2_CONTRACT_FILENAME,
    V3_SCHEMA_ID: V3_CONTRACT_FILENAME,
}

_SHA256_RE = re.compile(r"^[a-f0-9]{64}$")
ASSERTION_DISPOSITION_EXTERNAL = "EXTERNAL_PRIVATE_VERIFICATION_INPUT"

# -- authorship -------------------------------------------------------------

OPERATOR_INPUT = "operator_input"
OPERATOR_MATERIAL = "operator_material"
MACHINE_RESULT = "machine_result"
MODEL_PROSE = "model_prose"
MODEL_REASONING = "model_reasoning"
MODEL_TOOL_CALL = "model_tool_call"
TELEMETRY = "telemetry"
MIXED = "mixed"

AUTHORSHIP_CLASSES = frozenset(
    {
        OPERATOR_INPUT,
        OPERATOR_MATERIAL,
        MACHINE_RESULT,
        MODEL_PROSE,
        MODEL_REASONING,
        MODEL_TOOL_CALL,
        TELEMETRY,
        MIXED,
    }
)

#: Classes whose bytes originate with a third-party provider. Recorded so a
#: rights question can be scoped to the classes it actually applies to.
PROVIDER_AUTHORED = frozenset({MODEL_PROSE, MODEL_REASONING, MODEL_TOOL_CALL})

# -- rights -----------------------------------------------------------------

RIGHTS_UNKNOWN = "UNKNOWN"

#: Only these may be released. Everything else, including UNKNOWN and any term
#: not listed here, blocks.
ADMISSIBLE_RIGHTS_STATUS = frozenset(
    {
        # The release is a transformation; source material is excluded but
        # hash-bound, so provenance verifies without redistributing the source.
        "TRANSFORMED_RELEASE_TEXT_ONLY_SOURCE_MATERIAL_EXCLUDED",
        # Authored by the operator, or generated by operator-owned scenarios.
        "OPERATOR_OWNED_FULL_RIGHTS",
        "SYNTHETIC_ORIGINAL_FULL_RIGHTS",
        # Produced by the operator's own machine (tool output, exit codes).
        "MACHINE_RESULT_OPERATOR_OWNED",
    }
)

# -- privacy and review -----------------------------------------------------

ADMISSIBLE_PRIVACY_STATUS = frozenset(
    {
        "PASS_MANUAL_PUBLIC_REVIEW",
        "PASS_AUTOMATED_SCAN",
        "PASS_AUTOMATED_REDACTION",
        "PASS_AUTOMATED_SCAN_AND_MANUAL_REVIEW",
    }
)

#: Values must name automated and manual treatment distinctly, so a pack never
#: implies a human read a record when none did.
ADMISSIBLE_QUALITY_REVIEW = frozenset(
    {"MANUAL_REVIEW_PASS", "AUTOMATED_REVIEW_PASS", "AUTOMATED_REVIEW_PASS_MANUAL_SPOT_CHECK"}
)

MANUAL_REVIEW_VALUES = frozenset({"MANUAL_REVIEW_PASS", "AUTOMATED_REVIEW_PASS_MANUAL_SPOT_CHECK"})

# -- source status ----------------------------------------------------------

ADMISSIBLE_INGOT_STATUS = frozenset({"PASSED", None})
ADMISSIBLE_FOUNDRY_STATUS = frozenset({"PASS", None})

# -- splits -----------------------------------------------------------------

TRAIN = "train"
PREFERENCE = "preference"
HELDOUT = "heldout_eval"
SPLITS = frozenset({TRAIN, PREFERENCE, HELDOUT})

TRAINING_SPLITS = frozenset({TRAIN, PREFERENCE})

# -- reasoning policy -------------------------------------------------------

REASONING_EXCLUDE = "exclude"
REASONING_ALLOW = "allow"
REASONING_POLICIES = frozenset({REASONING_EXCLUDE, REASONING_ALLOW})


class PackRecordError(ValueError):
    """A record is malformed."""


def load_schema(schema_id: str = SCHEMA_ID) -> dict[str, Any]:
    """Load the exact declared record contract (v2 by default)."""
    try:
        filename = CONTRACT_FILENAMES[schema_id]
    except (KeyError, TypeError) as exc:
        raise PackRecordError(
            f"unsupported pack record schema_id {schema_id!r}; "
            f"expected one of {sorted(SUPPORTED_SCHEMA_IDS)}"
        ) from exc
    return json.loads(find_contract(filename).read_text(encoding="utf-8"))


def rights_assertion_sha256(assertion: dict[str, Any]) -> str:
    """Hash the exact operator assertion body, excluding its integrity field."""
    body = {
        key: assertion.get(key)
        for key in ("asserted_by", "asserted_at", "basis")
    }
    encoded = json.dumps(
        body,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
        allow_nan=False,
    ).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def validate_rights_assertion(assertion: Any) -> list[str]:
    """Validate the integrity-bound, deliberately non-secret rights assertion."""
    if not isinstance(assertion, dict):
        return ["rights_assertion must be an object"]
    expected_fields = {"asserted_by", "asserted_at", "basis", "assertion_sha256"}
    if set(assertion) != expected_fields:
        return ["rights_assertion fields differ from the v2 assertion contract"]
    for key in ("asserted_by", "asserted_at", "basis"):
        if not isinstance(assertion.get(key), str) or not assertion[key]:
            return [f"rights_assertion.{key} must be a nonempty string"]
    claimed = assertion.get("assertion_sha256")
    if not isinstance(claimed, str) or _SHA256_RE.fullmatch(claimed) is None:
        return ["rights_assertion.assertion_sha256 must be a lowercase SHA-256"]
    try:
        expected = rights_assertion_sha256(assertion)
    except (TypeError, ValueError, UnicodeError):
        return ["rights_assertion is not canonical JSON data"]
    if claimed != expected:
        return ["rights_assertion.assertion_sha256 differs from its canonical body"]
    return []


def validate_record(record: dict[str, Any]) -> list[str]:
    """Structural validation. Returns a list of problems; empty means valid."""
    errors: list[str] = []
    if not isinstance(record, dict):
        return ["record must be a JSON object"]

    schema_id = record.get("schema_id")
    schema_supported = isinstance(schema_id, str) and schema_id in SUPPORTED_SCHEMA_IDS
    if not schema_supported:
        errors.append(
            f"unsupported schema_id {schema_id!r}; expected one of {sorted(SUPPORTED_SCHEMA_IDS)}"
        )

    for key in (
        "record_id",
        "content_sha256",
        "authorship_class",
        "rights_status",
        "privacy_status",
        "quality_review",
        "derivation_method",
        "split",
        "split_group_id",
        "source",
    ):
        if not record.get(key):
            errors.append(f"missing required field: {key}")

    authorship = record.get("authorship_class")
    if authorship is not None and authorship not in AUTHORSHIP_CLASSES:
        errors.append(f"unknown authorship_class: {authorship!r}")

    split = record.get("split")
    if split is not None and split not in SPLITS:
        errors.append(f"unknown split: {split!r}")

    source = record.get("source")
    if isinstance(source, dict):
        if not source.get("source_hash_sha256"):
            errors.append("source.source_hash_sha256 is required for upward binding")
    elif source is not None:
        errors.append("source must be an object")

    if isinstance(schema_id, str) and schema_id in {V2_SCHEMA_ID, V3_SCHEMA_ID}:
        for key in (
            "released_row_sha256",
            "released_row_format",
            "privacy_receipt_sha256",
            "privacy_receipt_ref",
            "privacy_ruleset_sha256",
            "split_group_ids",
            "source_artifacts",
        ):
            value = record.get(key)
            if value is None or value == "" or value == []:
                errors.append(f"missing required v2 field: {key}")

        if schema_id == V2_SCHEMA_ID and "rights_assertion" not in record:
            errors.append("missing required v2 field: rights_assertion")
        if schema_id == V3_SCHEMA_ID:
            if record.get("rights_assertion") is not None:
                errors.append("v3 records must not carry a rights assertion body")
            binding = record.get("rights_assertion_binding")
            if not isinstance(binding, dict):
                errors.append("missing required v3 field: rights_assertion_binding")
            else:
                digest = binding.get("assertion_sha256")
                if not isinstance(digest, str) or _SHA256_RE.fullmatch(digest) is None:
                    errors.append(
                        "rights_assertion_binding.assertion_sha256 must be a lowercase SHA-256"
                    )
                if binding.get("disposition") != ASSERTION_DISPOSITION_EXTERNAL:
                    errors.append(
                        "rights_assertion_binding.disposition must be "
                        f"{ASSERTION_DISPOSITION_EXTERNAL}"
                    )

        for key in (
            "released_row_sha256",
            "privacy_receipt_sha256",
            "privacy_ruleset_sha256",
        ):
            value = record.get(key)
            if not isinstance(value, str) or _SHA256_RE.fullmatch(value) is None:
                errors.append(f"{key} must be a lowercase 64-character SHA-256")

        groups = record.get("split_group_ids")
        if not isinstance(groups, list) or not groups:
            errors.append("split_group_ids must be a nonempty array")
        elif not all(isinstance(group, str) and group for group in groups):
            errors.append("split_group_ids entries must be nonempty strings")
        else:
            if len(groups) != len(set(groups)):
                errors.append("split_group_ids entries must be unique")
            if record.get("split_group_id") not in groups:
                errors.append("split_group_ids must contain split_group_id")

        artifacts = record.get("source_artifacts")
        if not isinstance(artifacts, list) or not artifacts:
            errors.append("source_artifacts must be a nonempty array")
        else:
            for index, artifact in enumerate(artifacts):
                if not isinstance(artifact, dict):
                    errors.append(f"source_artifacts[{index}] must be an object")
                    continue
                if not isinstance(artifact.get("role"), str) or not artifact.get("role"):
                    errors.append(f"source_artifacts[{index}].role must be a nonempty string")
                sha256 = artifact.get("sha256")
                if not isinstance(sha256, str) or _SHA256_RE.fullmatch(sha256) is None:
                    errors.append(
                        f"source_artifacts[{index}].sha256 must be a lowercase 64-character SHA-256"
                    )

        assertion = record.get("rights_assertion")
        if schema_id == V2_SCHEMA_ID:
            if assertion is not None:
                errors.extend(validate_rights_assertion(assertion))
            if record.get("rights_status") in ADMISSIBLE_RIGHTS_STATUS and assertion is None:
                errors.append("admissible v2 rights_status requires rights_assertion")

    # An unknown version cannot be routed to a trustworthy contract. The
    # manually collected errors above are sufficient to fail closed.
    if not schema_supported:
        return errors

    try:
        import jsonschema
    except ImportError as exc:  # pragma: no cover - jsonschema is a base dependency
        errors.append(f"schema validator unavailable (install jsonschema): {exc}")
    else:
        try:
            jsonschema.Draft202012Validator(load_schema(str(schema_id))).validate(record)
        except Exception as exc:
            errors.append(f"schema: {exc}")
    return errors


def _record_split_group_ids(record: dict[str, Any]) -> frozenset[str]:
    """Return every usable leakage key, including the legacy primary key."""
    groups: set[str] = set()
    primary = record.get("split_group_id")
    if isinstance(primary, str) and primary:
        groups.add(primary)
    candidates = record.get("split_group_ids")
    if isinstance(candidates, list):
        groups.update(group for group in candidates if isinstance(group, str) and group)
    return frozenset(groups)


@dataclass(frozen=True)
class AdmissionDecision:
    """Why a record may or may not reach ``training-ready/``."""

    record_id: str
    admitted: bool
    reasons: tuple[str, ...] = ()
    checks: dict[str, str] = field(default_factory=dict)

    def as_dict(self) -> dict[str, Any]:
        return {
            "record_id": self.record_id,
            "admitted": self.admitted,
            "reasons": list(self.reasons),
            "checks": dict(self.checks),
        }


def admit_to_training_ready(
    record: dict[str, Any],
    *,
    heldout_group_ids: Iterable[str] = (),
    reasoning_policy: str = REASONING_EXCLUDE,
    admissible_rights: Iterable[str] | None = None,
) -> AdmissionDecision:
    """Decide whether one record may be published into ``training-ready/``.

    Never raises on a business rule: it returns a decision naming every reason,
    so a rejected record can be reported rather than lost. A malformed record is
    rejected too — validity is a precondition of admission, not an alternative
    to it.
    """
    if reasoning_policy not in REASONING_POLICIES:
        raise PackRecordError(
            f"unknown reasoning_policy {reasoning_policy!r}; expected one of {sorted(REASONING_POLICIES)}"
        )

    rights_allow = (
        ADMISSIBLE_RIGHTS_STATUS
        if admissible_rights is None
        else frozenset(admissible_rights)
    )
    record_id = str(record.get("record_id") or "<no record_id>")
    reasons: list[str] = []
    checks: dict[str, str] = {}

    problems = validate_record(record)
    if problems:
        checks["schema"] = "FAIL"
        reasons.append(f"record is not valid: {problems[0]}")
        return AdmissionDecision(record_id, False, tuple(reasons), checks)
    checks["schema"] = "PASS"

    # A held-out record is never a training input, whatever else is true.
    split = record.get("split")
    if split == HELDOUT:
        checks["split"] = "HELD_OUT"
        reasons.append("record is in the held-out evaluation split")
    else:
        checks["split"] = "PASS"

    # 1. rights
    rights = str(record.get("rights_status"))
    assertion_ok = (
        record.get("schema_id") != V2_SCHEMA_ID
        or not validate_rights_assertion(record.get("rights_assertion"))
    )
    if rights in rights_allow and assertion_ok:
        checks["rights"] = "PASS"
    else:
        checks["rights"] = "BLOCKED"
        if rights not in rights_allow:
            reasons.append(
                f"rights_status {rights!r} is not admissible"
                + (" (the default; assert rights explicitly)" if rights == RIGHTS_UNKNOWN else "")
            )
        else:
            reasons.append("v2 rights assertion is missing, malformed, or not integrity-bound")

    # 2. authorship
    authorship = str(record.get("authorship_class"))
    if authorship == MIXED:
        checks["authorship"] = "BLOCKED"
        reasons.append("authorship_class is 'mixed'; split the record into single-class records first")
    elif authorship == MODEL_REASONING and reasoning_policy == REASONING_EXCLUDE:
        checks["authorship"] = "BLOCKED"
        reasons.append("model reasoning is excluded by the active reasoning policy")
    else:
        checks["authorship"] = "PASS"

    # 3. privacy
    privacy = str(record.get("privacy_status"))
    if privacy in ADMISSIBLE_PRIVACY_STATUS:
        checks["privacy"] = "PASS"
    else:
        checks["privacy"] = "BLOCKED"
        reasons.append(f"privacy_status {privacy!r} does not record a passed scan")

    review = str(record.get("quality_review"))
    if review in ADMISSIBLE_QUALITY_REVIEW:
        checks["quality_review"] = "PASS"
    else:
        checks["quality_review"] = "BLOCKED"
        reasons.append(f"quality_review {review!r} is not an admissible review outcome")

    # 4. leakage group
    groups = _record_split_group_ids(record)
    overlap = groups.intersection(str(group) for group in heldout_group_ids)
    if overlap:
        checks["leakage"] = "BLOCKED"
        reasons.append(
            f"split_group_ids {sorted(overlap)!r} also appear in the held-out split"
        )
    else:
        checks["leakage"] = "PASS"

    # 5. source status
    source = record.get("source") or {}
    ingot_status = source.get("source_ingot_status")
    foundry_status = source.get("source_foundry_status")
    if record.get("schema_id") == V3_SCHEMA_ID:
        source_status_ok = (
            foundry_status == "PASS"
            and ingot_status in {"PASSED", "RIGHTS_ASSERTED"}
        )
    elif record.get("schema_id") == V2_SCHEMA_ID:
        source_status_ok = ingot_status == "PASSED" and foundry_status == "PASS"
    else:
        # Legacy v1 did not require explicit status fields. Retain its historical
        # behavior without weakening the v2 producer contract.
        source_status_ok = (
            ingot_status in ADMISSIBLE_INGOT_STATUS
            and foundry_status in ADMISSIBLE_FOUNDRY_STATUS
        )
    if source_status_ok:
        checks["source_status"] = "PASS"
    else:
        checks["source_status"] = "BLOCKED"
        reasons.append(
            f"source ingot status {ingot_status!r} / Foundry status {foundry_status!r} is not admissible"
        )

    return AdmissionDecision(record_id, not reasons, tuple(reasons), checks)


def partition_records(
    records: Iterable[dict[str, Any]],
    *,
    reasoning_policy: str = REASONING_EXCLUDE,
    admissible_rights: Iterable[str] | None = None,
) -> dict[str, Any]:
    """Split a record set into what may be released and what may not.

    Held-out group ids are derived from the records themselves, so a leakage
    group cannot be missed by a caller forgetting to pass it in.
    """
    records = list(records)
    heldout_groups: set[str] = set()
    for record in records:
        if isinstance(record, dict) and record.get("split") == HELDOUT:
            heldout_groups.update(_record_split_group_ids(record))

    admitted: list[dict[str, Any]] = []
    rejected: list[dict[str, Any]] = []
    decisions: list[AdmissionDecision] = []
    for record in records:
        decision = admit_to_training_ready(
            record,
            heldout_group_ids=heldout_groups,
            reasoning_policy=reasoning_policy,
            admissible_rights=admissible_rights,
        )
        decisions.append(decision)
        (admitted if decision.admitted else rejected).append(record)

    reason_counts: dict[str, int] = {}
    for decision in decisions:
        for reason in decision.reasons:
            key = reason.split(";")[0].split("(")[0].strip()
            reason_counts[key] = reason_counts.get(key, 0) + 1

    return {
        "reasoning_policy": reasoning_policy,
        "heldout_group_ids": sorted(heldout_groups),
        "counts": {
            "total": len(records),
            "admitted": len(admitted),
            "rejected": len(rejected),
        },
        "admitted": admitted,
        "rejected": rejected,
        "decisions": [d.as_dict() for d in decisions],
        "rejection_reasons": dict(sorted(reason_counts.items(), key=lambda kv: -kv[1])),
    }
